// lib/courses.ts

export type InstrutorInfo = {
  nome: string
  descricao: string
}

export type Course = {
  id: number
  titulo: string
  subtitulo: string | null
  categoria: string
  bg: string
  shadow: string
  textColor: string
  emoji: string
  preco: string
  productId: string
  imagem?: string
  slug: string
  descricaoCurta: string
  descricaoLonga: string

  // ── novos campos ──────────────────────────────────────
  publicoAlvo?: string
  cargaHorariaDetalhe?: string
  oQueVaiAprender?: string[]
  instrutor?: InstrutorInfo
  informacoesCurso?: string[]
}

type CourseInput = Omit<Course, 'slug' | 'descricaoCurta' | 'descricaoLonga'> & {
  descricaoCurta?: string
  descricaoLonga?: string
}

// ─────────────────────────────────────────────────────────────────────────
// Slug automático a partir do título (+ subtítulo se houver, + id se colidir)
// ─────────────────────────────────────────────────────────────────────────
function slugify(texto: string): string {
  return texto
    .normalize('NFD').replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '')
}

function gerarDescricaoPadrao(c: CourseInput): string {
  return `O curso ${c.titulo}${c.subtitulo ? ` (${c.subtitulo})` : ''} faz parte da categoria ${c.categoria} e foi desenvolvido para atender às exigências do CONTRAN/DETRAN, com conteúdo teórico completo, material de apoio e certificado válido em todo o território nacional.`
}

// ─────────────────────────────────────────────────────────────────────────
// Cole aqui os cursos exatamente como já estavam, só que sem "slug"
// (adicione descricaoCurta/descricaoLonga manualmente quando quiser
// personalizar; se não colocar, um texto padrão é gerado automaticamente)
// ─────────────────────────────────────────────────────────────────────────
const coursesInput: CourseInput[] = [
  // ─── FORMAÇÃO ESPECIALIZADA ───────────────────────────────────────────
  { id: 1, titulo: 'Carga Indivisível Formação', subtitulo: 'CETCI', categoria: 'Formação', bg: 'from-yellow-400 to-yellow-500', shadow: 'shadow-yellow-300', textColor: 'text-yellow-900', emoji: '🚛', preco: 'R$ 260,00', productId: 'prod_PUsCwUrUYwwhuydfmN4HtFu6', imagem: '/img/CARGA_INDIVISIVEL.png', publicoAlvo: 'Condutores que atuam no transporte de carga indivisível e precisam atender aos requisitos da formação.', cargaHorariaDetalhe: 'CETCI', oQueVaiAprender: ['Legislação e requisitos do curso', 'Direção defensiva e segurança', 'Noções de primeiros socorros', 'Boas práticas de transporte'], instrutor: { nome: 'LM', descricao: 'Instrutor responsável pelo curso.' }, informacoesCurso: ['Curso 100% online', 'Material de apoio incluso', 'Certificado ao final', 'Acesso por 12 meses'] },
  { id: 2, titulo: 'Coletivo de Passageiros Formação', subtitulo: 'CETCP', categoria: 'Formação', bg: 'from-yellow-400 to-yellow-500', shadow: 'shadow-yellow-300', textColor: 'text-yellow-900', emoji: '🚌', preco: 'R$ 260,00', productId: 'prod_PcgrqBLyNUGmLhJqg6aPzUpP', imagem: '/img/COLETIVO.png', publicoAlvo: 'Profissionais que atuam no transporte coletivo de passageiros e precisam concluir a formação.', cargaHorariaDetalhe: 'CETCP', oQueVaiAprender: ['Legislação e requisitos do curso', 'Direção defensiva e segurança', 'Noções de primeiros socorros', 'Boas práticas de transporte'], instrutor: { nome: 'LM', descricao: 'Instrutor responsável pelo curso.' }, informacoesCurso: ['Curso 100% online', 'Material de apoio incluso', 'Certificado ao final', 'Acesso por 12 meses'] },
  { id: 3, titulo: 'Emergência Formação', subtitulo: 'CETVE', categoria: 'Formação', bg: 'from-yellow-400 to-yellow-500', shadow: 'shadow-yellow-300', textColor: 'text-yellow-900', emoji: '🚑', preco: 'R$ 260,00', productId: 'prod_fYsaJFATU3ZznqUkW0gmxfUz', imagem: '/img/EMERGÊNCIA.png', publicoAlvo: 'Condutores de veículos de emergência que precisam atender ao requisito de formação.', cargaHorariaDetalhe: 'CETVE', oQueVaiAprender: ['Legislação e requisitos do curso', 'Direção defensiva e segurança', 'Noções de primeiros socorros', 'Boas práticas de transporte'], instrutor: { nome: 'LM', descricao: 'Instrutor responsável pelo curso.' }, informacoesCurso: ['Curso 100% online', 'Material de apoio incluso', 'Certificado ao final', 'Acesso por 12 meses'] },
  { id: 4, titulo: 'Escolar Formação', subtitulo: 'CETE', categoria: 'Formação', bg: 'from-yellow-400 to-yellow-500', shadow: 'shadow-yellow-300', textColor: 'text-yellow-900', emoji: '🏫', preco: 'R$ 260,00', productId: 'prod_r4BZPqU1Hx42xDuYxeFZE2FC', imagem: '/img/escolar.png', publicoAlvo: 'Condutores e profissionais do transporte escolar que precisam concluir a formação.', cargaHorariaDetalhe: 'CETE', oQueVaiAprender: ['Legislação e requisitos do curso', 'Direção defensiva e segurança', 'Noções de primeiros socorros', 'Boas práticas de transporte'], instrutor: { nome: 'LM', descricao: 'Instrutor responsável pelo curso.' }, informacoesCurso: ['Curso 100% online', 'Material de apoio incluso', 'Certificado ao final', 'Acesso por 12 meses'] },
  { id: 5, titulo: 'Produtos Perigosos - MOPP Formação', subtitulo: 'CETPP', categoria: 'Formação', bg: 'from-yellow-400 to-yellow-500', shadow: 'shadow-yellow-300', textColor: 'text-yellow-900', emoji: '☢️', preco: 'R$ 260,00', productId: 'prod_32C2Nf1jG2AHQ1UFAzxLDjhZ', imagem: '/img/PRODUTOS_PERIGOSOS.png', publicoAlvo: 'Condutores que transportam produtos perigosos e precisam cumprir a formação exigida.', cargaHorariaDetalhe: 'CETPP', oQueVaiAprender: ['Legislação e requisitos do curso', 'Direção defensiva e segurança', 'Noções de primeiros socorros', 'Boas práticas de transporte'], instrutor: { nome: 'LM', descricao: 'Instrutor responsável pelo curso.' }, informacoesCurso: ['Curso 100% online', 'Material de apoio incluso', 'Certificado ao final', 'Acesso por 12 meses'] },

  // ─── ATUALIZAÇÃO ESPECIALIZADA ────────────────────────────────────────
  { id: 6, titulo: 'Carga Indivisível Atualização', subtitulo: 'CETCI', categoria: 'Atualização', bg: 'from-blue-500 to-blue-600', shadow: 'shadow-blue-300', textColor: 'text-white', emoji: '🚛', preco: 'R$ 220,00', productId: 'prod_Q5bMzN2WHwTQwHkCdSXYGKeZ', imagem: '/img/CARGA_INDIVISIVEL_ATUALIZACAO.png', publicoAlvo: 'Condutores que já possuem a formação e precisam renovar ou atualizar o conhecimento.', cargaHorariaDetalhe: 'CETCI', oQueVaiAprender: ['Legislação e requisitos da atualização', 'Direção defensiva e segurança', 'Noções de primeiros socorros', 'Procedimentos de transporte'], instrutor: { nome: 'LM', descricao: 'Instrutor responsável pelo curso.' }, informacoesCurso: ['Curso 100% online', 'Material de apoio incluso', 'Certificado ao final', 'Acesso por 12 meses'] },
  { id: 7, titulo: 'Coletivo de Passageiros Atualização', subtitulo: 'CETCP', categoria: 'Atualização', bg: 'from-blue-500 to-blue-600', shadow: 'shadow-blue-300', textColor: 'text-white', emoji: '🚌', preco: 'R$ 220,00', productId: 'prod_DyTkNx5MmTEn0HdYGGYKAP3n', imagem: '/img/COLETIVO_ATUALIZACAO.png', publicoAlvo: 'Condutores do transporte coletivo que precisam manter a atualização em dia.', cargaHorariaDetalhe: 'CETCP', oQueVaiAprender: ['Legislação e requisitos da atualização', 'Direção defensiva e segurança', 'Noções de primeiros socorros', 'Procedimentos de transporte'], instrutor: { nome: 'LM', descricao: 'Instrutor responsável pelo curso.' }, informacoesCurso: ['Curso 100% online', 'Material de apoio incluso', 'Certificado ao final', 'Acesso por 12 meses'] },
  { id: 8, titulo: 'Emergência Atualização', subtitulo: 'CETVE', categoria: 'Atualização', bg: 'from-blue-500 to-blue-600', shadow: 'shadow-blue-300', textColor: 'text-white', emoji: '🚑', preco: 'R$ 220,00', productId: 'prod_1nrTQHXEnkWPQbpQtWKE2tQJ', imagem: '/img/EMERGENCIA_ATUALIZACAO.png', publicoAlvo: 'Condutores de veículos de emergência que precisam manter a formação atualizada.', cargaHorariaDetalhe: 'CETVE', oQueVaiAprender: ['Legislação e requisitos da atualização', 'Direção defensiva e segurança', 'Noções de primeiros socorros', 'Procedimentos de transporte'], instrutor: { nome: 'LM', descricao: 'Instrutor responsável pelo curso.' }, informacoesCurso: ['Curso 100% online', 'Material de apoio incluso', 'Certificado ao final', 'Acesso por 12 meses'] },
  { id: 9, titulo: 'Escolar Atualização', subtitulo: 'CETE', categoria: 'Atualização', bg: 'from-blue-500 to-blue-600', shadow: 'shadow-blue-300', textColor: 'text-white', emoji: '🏫', preco: 'R$ 220,00', productId: 'prod_uwTbzdBNFABwBM4jh3hUZXKa', imagem: '/img/ESCOLAR_ATUALIZACAO.png', publicoAlvo: 'Profissionais do transporte escolar que precisam manter a atualização em dia.', cargaHorariaDetalhe: 'CETE', oQueVaiAprender: ['Legislação e requisitos da atualização', 'Direção defensiva e segurança', 'Noções de primeiros socorros', 'Procedimentos de transporte'], instrutor: { nome: 'LM', descricao: 'Instrutor responsável pelo curso.' }, informacoesCurso: ['Curso 100% online', 'Material de apoio incluso', 'Certificado ao final', 'Acesso por 12 meses'] },
  { id: 10, titulo: 'Produtos Perigosos - MOPP Atualização', subtitulo: 'CETPP', categoria: 'Atualização', bg: 'from-blue-500 to-blue-600', shadow: 'shadow-blue-300', textColor: 'text-white', emoji: '☢️', preco: 'R$ 220,00', productId: 'prod_Aub4S2MtFtdbSZrCJAmkfCpY', imagem: '/img/MOPP_ATUALIZAÇÃO.png', publicoAlvo: 'Condutores que transportam produtos perigosos e precisam manter o curso atualizado.', cargaHorariaDetalhe: 'CETPP', oQueVaiAprender: ['Legislação e requisitos da atualização', 'Direção defensiva e segurança', 'Noções de primeiros socorros', 'Procedimentos de transporte'], instrutor: { nome: 'LM', descricao: 'Instrutor responsável pelo curso.' }, informacoesCurso: ['Curso 100% online', 'Material de apoio incluso', 'Certificado ao final', 'Acesso por 12 meses'] },

  // ─── RECICLAGEM CNH ────────────────────────────────────────────────────
  { id: 11, titulo: 'Atualização para Renovação da CNH', subtitulo: null, categoria: 'Reciclagem', bg: 'from-red-500 to-red-600', shadow: 'shadow-red-300', textColor: 'text-white', emoji: '🔄', preco: 'R$ 100,00', productId: 'prod_gHJkfUepXhqtxum1XZUwF4Y6', imagem: '/img/CURSO_RECICLAGEM.png', publicoAlvo: 'Condutores que precisam cumprir a reciclagem ou renovação da CNH.', cargaHorariaDetalhe: 'Carga horária a definir', oQueVaiAprender: ['Legislação e requisitos para reciclagem', 'Atualização de normas de trânsito', 'Aspectos práticos da condução segura', 'Orientações para manutenção da habilitação'], instrutor: { nome: 'LM', descricao: 'Instrutor responsável pelo curso.' }, informacoesCurso: ['Conteúdo teórico e prático', 'Material de apoio em PDF incluso', 'Certificado ao final do curso', 'Acesso ao curso por 12 meses'] },
  { id: 12, titulo: 'Curso Preventivo de Reciclagem', subtitulo: null, categoria: 'Reciclagem', bg: 'from-red-500 to-red-600', shadow: 'shadow-red-300', textColor: 'text-white', emoji: '🔄', preco: 'R$ 100,00', productId: 'prod_DE0aKME2rpnJUr5wJUKRPZTC', imagem: '/img/CURSO_RECICLAGEM.png', publicoAlvo: 'Condutores que precisam reduzir pontos e manter a CNH regular.', cargaHorariaDetalhe: 'Carga horária a definir', oQueVaiAprender: ['Legislação e requisitos para reciclagem', 'Atualização de normas de trânsito', 'Aspectos práticos da condução segura', 'Orientações para manutenção da habilitação'], instrutor: { nome: 'LM', descricao: 'Instrutor responsável pelo curso.' }, informacoesCurso: ['Conteúdo teórico e prático', 'Material de apoio em PDF incluso', 'Certificado ao final do curso', 'Acesso ao curso por 12 meses'] },
  { id: 13, titulo: 'Reciclagem para Condutores Infratores', subtitulo: null, categoria: 'Reciclagem', bg: 'from-red-500 to-red-600', shadow: 'shadow-red-300', textColor: 'text-white', emoji: '⚠️', preco: 'R$ 100,00', productId: 'prod_zD60RGkYnJWRNSp2xEYbUw4c', imagem: '/img/CURSO_RECICLAGEM_2021.png', publicoAlvo: 'Condutores infratores que precisam cumprir a reciclagem exigida pelo trânsito.', cargaHorariaDetalhe: 'Carga horária a definir', oQueVaiAprender: ['Legislação e requisitos para reciclagem', 'Atualização de normas de trânsito', 'Aspectos práticos da condução segura', 'Orientações para manutenção da habilitação'], instrutor: { nome: 'LM', descricao: 'Instrutor responsável pelo curso.' }, informacoesCurso: ['Conteúdo teórico e prático', 'Material de apoio em PDF incluso', 'Certificado ao final do curso', 'Acesso ao curso por 12 meses'] },

  // ─── TAXISTA / APP ─────────────────────────────────────────────────────
  { id: 14, titulo: 'Curso para Taxista', subtitulo: null, categoria: 'Profissional', bg: 'from-emerald-500 to-green-600', shadow: 'shadow-emerald-300', textColor: 'text-white', emoji: '🚕', preco: 'R$ 180,00', productId: 'prod_ZknCmFdTpb1sFGYuxFAkSGzG', imagem: '/img/TAXISTA.png', publicoAlvo: 'Motoristas de táxi que precisam conhecer a legislação e requisitos da profissão.', cargaHorariaDetalhe: 'Carga horária a definir', oQueVaiAprender: ['Legislação do serviço de táxi', 'Atendimento ao cliente e segurança', 'Conhecimento da profissão e procedimentos', 'Boas práticas operacionais'], instrutor: { nome: 'LM', descricao: 'Instrutor responsável pelo curso.' }, informacoesCurso: ['Conteúdo teórico e prático', 'Material de apoio em PDF incluso', 'Certificado ao final do curso', 'Acesso ao curso por 12 meses'] },
  { id: 15, titulo: 'Curso para Condutor de App', subtitulo: null, categoria: 'Profissional', bg: 'from-emerald-500 to-green-600', shadow: 'shadow-emerald-300', textColor: 'text-white', emoji: '📱', preco: 'R$ 180,00', productId: 'prod_1JDCwETAsrp25TmWzbQarwgX', imagem: '/img/CURSO_CONDUTORES_APP.png', publicoAlvo: 'Motoristas que atuam ou desejam atuar em serviços de transporte de aplicativo.', cargaHorariaDetalhe: 'Carga horária a definir', oQueVaiAprender: ['Legislação do transporte de aplicativo', 'Atendimento ao cliente e segurança', 'Conhecimento da profissão e procedimentos', 'Boas práticas operacionais'], instrutor: { nome: 'LM', descricao: 'Instrutor responsável pelo curso.' }, informacoesCurso: ['Conteúdo teórico e prático', 'Material de apoio em PDF incluso', 'Certificado ao final do curso', 'Acesso ao curso por 12 meses'] },

  // ─── MOTO ──────────────────────────────────────────────────────────────
  { id: 16, titulo: 'Motofrete Atualização', subtitulo: '100% online', categoria: 'Moto', bg: 'from-orange-400 to-orange-500', shadow: 'shadow-orange-300', textColor: 'text-orange-900', emoji: '🏍️', preco: 'R$ 260,00', productId: 'prod_6MAUQZD2J6HHtrfFUYFMTSft', imagem: '/img/motofrete1.png', publicoAlvo: 'Motofretistas que precisam manter a atualização do curso em dia.', cargaHorariaDetalhe: '100% online', oQueVaiAprender: ['Regras do transporte por motocicleta', 'Segurança na condução e atendimento', 'Procedimentos de uso do veículo', 'Boas práticas para trabalho e atendimento'], instrutor: { nome: 'LM', descricao: 'Instrutor responsável pelo curso.' }, informacoesCurso: ['Conteúdo teórico e prático', 'Material de apoio em PDF incluso', 'Certificado emitido ao final do curso', 'Acesso ao curso por 12 meses'] },
  { id: 17, titulo: 'Motofrete Formação', subtitulo: '100% online', categoria: 'Moto', bg: 'from-orange-400 to-orange-500', shadow: 'shadow-orange-300', textColor: 'text-orange-900', emoji: '🏍️', preco: 'R$ 260,00', productId: 'prod_zbuEqmwwW6cnht2sR5SbPwYC', imagem: '/img/motofrete2.png', publicoAlvo: 'Profissionais que realizam entregas por motocicleta e precisam da formação obrigatória.', cargaHorariaDetalhe: '100% online', oQueVaiAprender: ['Legislação específica de motofrete', 'Equipamentos obrigatórios', 'Dispositivos de fixação de carga', 'Direção defensiva e manutenção'], instrutor: { nome: 'LM', descricao: 'Instrutor responsável pelo curso.' }, informacoesCurso: ['Conteúdo teórico e prático', 'Material de apoio em PDF incluso', 'Certificado ao final do curso', 'Acesso ao curso por 12 meses'] },
  { id: 18, titulo: 'Mototáxi Atualização', subtitulo: '100% online', categoria: 'Moto', bg: 'from-orange-400 to-orange-500', shadow: 'shadow-orange-300', textColor: 'text-orange-900', emoji: '🛵', preco: 'R$ 260,00', productId: 'prod_CNYuZBfJHsaUpym2WqncYxCB', imagem: '/img/mototaxi1.png', publicoAlvo: 'Mototaxistas que precisam manter a atualização do curso em dia.', cargaHorariaDetalhe: '100% online', oQueVaiAprender: ['Regras do transporte por motocicleta', 'Segurança na condução e atendimento', 'Procedimentos de uso do veículo', 'Boas práticas para trabalho e atendimento'], instrutor: { nome: 'LM', descricao: 'Instrutor responsável pelo curso.' }, informacoesCurso: ['Conteúdo teórico e prático', 'Material de apoio em PDF incluso', 'Certificado emitido ao final do curso', 'Acesso ao curso por 12 meses'] },
  { id: 19, titulo: 'Mototáxi Formação', subtitulo: '100% online', categoria: 'Moto', bg: 'from-orange-400 to-orange-500', shadow: 'shadow-orange-300', textColor: 'text-orange-900', emoji: '🛵', preco: 'R$ 260,00', productId: 'prod_zyPqf1X16X2hhKXSekRyBbAT', imagem: '/img/mototaxi2.png', publicoAlvo: 'Condutores que desejam atuar no transporte de passageiros por motocicleta.', cargaHorariaDetalhe: '100% online', oQueVaiAprender: ['Legislação aplicada', 'Equipamentos obrigatórios', 'Comportamento seguro', 'Técnicas de pilotagem defensiva'], instrutor: { nome: 'LM', descricao: 'Instrutor responsável pelo curso.' }, informacoesCurso: ['Conteúdo teórico e prático', 'Material de apoio em PDF incluso', 'Certificado ao final do curso', 'Acesso ao curso por 12 meses'] },

  // ─── NORMAS REGULAMENTADORAS (NR) ──────────────────────────────────────
  { id: 20, titulo: 'Operador de Empilhadeiras Atualização', subtitulo: '100% online', categoria: 'NR', bg: 'from-purple-500 to-purple-700', shadow: 'shadow-purple-300', textColor: 'text-white', emoji: '🏗️', preco: 'R$ 130,00', productId: 'prod_RDZ3yL0MhffHpqFzY5dQmphr', imagem: '/img/empilhadeira.webp', publicoAlvo: 'Operadores e profissionais que trabalham com empilhadeiras e movimentação de materiais.', cargaHorariaDetalhe: '100% online', oQueVaiAprender: ['Fundamentos do tema do curso', 'Procedimentos de segurança e conformidade', 'Aplicação prática no dia a dia profissional', 'Atualização de conhecimentos e boas práticas'], instrutor: { nome: 'LM', descricao: 'Instrutor responsável pelo curso.' }, informacoesCurso: ['Conteúdo teórico e prático', 'Material de apoio em PDF incluso', 'Certificado ao final do curso', 'Acesso ao curso por 12 meses'] },
  { id: 21, titulo: 'NR 06', subtitulo: '16h', categoria: 'NR', bg: 'from-purple-500 to-purple-700', shadow: 'shadow-purple-300', textColor: 'text-white', emoji: '🦺', preco: 'R$ 130,00', productId: 'prod_YfUwJWPt4aNCEgkamCp6pwhf', imagem: '/img/NR06.png', publicoAlvo: 'Profissionais que atuam com EPI e precisam conhecer as exigências da NR 06.', cargaHorariaDetalhe: '16h', oQueVaiAprender: ['Requisitos de EPI e uso adequado', 'Normas e procedimentos da NR 06', 'Riscos ocupacionais e prevenção', 'Boas práticas de segurança no trabalho'], instrutor: { nome: 'LM', descricao: 'Instrutor responsável pelo curso.' }, informacoesCurso: ['Conteúdo em conformidade com a legislação vigente', 'Material de apoio em PDF incluso', 'Certificado emitido ao final do curso', 'Acesso ao conteúdo por 12 meses'] },
  { id: 22, titulo: 'NR 10', subtitulo: '40h', categoria: 'NR', bg: 'from-purple-500 to-purple-700', shadow: 'shadow-purple-300', textColor: 'text-white', emoji: '⚡', preco: 'R$ 130,00', productId: 'prod_fTeuBgnEpN221skRAGSqU6Cx', imagem: '/img/NR10.png', publicoAlvo: 'Técnicos, eletricistas e profissionais que atuam em instalações elétricas e serviços com eletricidade.', cargaHorariaDetalhe: '40h', oQueVaiAprender: ['Riscos elétricos e medidas de controle', 'Normas e procedimentos da NR 10', 'Uso de EPI e EPC em instalações elétricas', 'Primeiros socorros e atendimento em acidentes elétricos'], instrutor: { nome: 'LM', descricao: 'Instrutor responsável pelo curso.' }, informacoesCurso: ['Conteúdo em conformidade com a legislação vigente', 'Material de apoio em PDF incluso', 'Certificado emitido ao final do curso', 'Acesso ao conteúdo por 12 meses'] },
  { id: 23, titulo: 'NR 11', subtitulo: '16h', categoria: 'NR', bg: 'from-purple-500 to-purple-700', shadow: 'shadow-purple-300', textColor: 'text-white', emoji: '📦', preco: 'R$ 130,00', productId: 'prod_fwEeRgE5ZDLqpzgtsc1U5DeG', imagem: '/img/NR11.png', publicoAlvo: 'Operadores e profissionais que movimentam, armazenam e manuseiam materiais em ambiente de trabalho.', cargaHorariaDetalhe: '16h', oQueVaiAprender: ['Movimentação e armazenamento seguro de materiais', 'Procedimentos de carga e descarga', 'Prevenção de acidentes e lesões', 'Boas práticas em ambientes de trabalho'], instrutor: { nome: 'LM', descricao: 'Instrutor responsável pelo curso.' }, informacoesCurso: ['Conteúdo em conformidade com a legislação vigente', 'Material de apoio em PDF incluso', 'Certificado emitido ao final do curso', 'Acesso ao conteúdo por 12 meses'] },
  { id: 24, titulo: 'NR 12', subtitulo: '16h', categoria: 'NR', bg: 'from-purple-500 to-purple-700', shadow: 'shadow-purple-300', textColor: 'text-white', emoji: '⚙️', preco: 'R$ 130,00', productId: 'prod_YYRpgu4DCteHw6ukw4N4EeAD', imagem: '/img/NR12.png', publicoAlvo: 'Profissionais que operam máquinas e equipamentos e precisam seguir as normas de segurança.', cargaHorariaDetalhe: '16h', oQueVaiAprender: ['Segurança em máquinas e equipamentos', 'Medidas preventivas e de controle', 'Procedimentos operacionais seguros', 'Identificação de riscos e acidentes'], instrutor: { nome: 'LM', descricao: 'Instrutor responsável pelo curso.' }, informacoesCurso: ['Conteúdo em conformidade com a legislação vigente', 'Material de apoio em PDF incluso', 'Certificado emitido ao final do curso', 'Acesso ao conteúdo por 12 meses'] },
  { id: 25, titulo: 'NR 16', subtitulo: '16h', categoria: 'NR', bg: 'from-purple-500 to-purple-700', shadow: 'shadow-purple-300', textColor: 'text-white', emoji: '🔥', preco: 'R$ 130,00', productId: 'prod_jtmcEKqcAEqHwShtMRSEHkYk', imagem: '/img/nr16.png', publicoAlvo: 'Trabalhadores e supervisores em atividades e operações perigosas.', cargaHorariaDetalhe: '16h', oQueVaiAprender: ['Atividades e operações perigosas', 'Medidas de controle e prevenção', 'Legislação específica da NR 16', 'Boas práticas operacionais'], instrutor: { nome: 'LM', descricao: 'Instrutor responsável pelo curso.' }, informacoesCurso: ['Conteúdo em conformidade com a legislação vigente', 'Material de apoio em PDF incluso', 'Certificado emitido ao final do curso', 'Acesso ao conteúdo por 12 meses'] },
  { id: 26, titulo: 'NR 20 - Básico', subtitulo: '8h', categoria: 'NR', bg: 'from-purple-500 to-purple-700', shadow: 'shadow-purple-300', textColor: 'text-white', emoji: '🛢️', preco: 'R$ 130,00', productId: 'prod_umghGpJXNNp6gHK4NdXgL6CY', imagem: '/img/NR20.png', publicoAlvo: 'Profissionais que atuam com inflamáveis, combustíveis e processos industriais relacionados à NR 20.', cargaHorariaDetalhe: '8h', oQueVaiAprender: ['Riscos com inflamáveis e combustíveis', 'Procedimentos de segurança e prevenção', 'Normas específicas da NR 20', 'Condutas adequadas em operações industriais'], instrutor: { nome: 'LM', descricao: 'Instrutor responsável pelo curso.' }, informacoesCurso: ['Conteúdo em conformidade com a legislação vigente', 'Material de apoio em PDF incluso', 'Certificado emitido ao final do curso', 'Acesso ao conteúdo por 12 meses'] },
  { id: 27, titulo: 'NR 20 - Intermediário Classe 01', subtitulo: null, categoria: 'NR', bg: 'from-purple-500 to-purple-700', shadow: 'shadow-purple-300', textColor: 'text-white', emoji: '🛢️', preco: 'R$ 130,00', productId: 'prod_bwAwNXdbfz11AyhRjpfFbhFW', imagem: '/img/NR20 ClasseI.png', publicoAlvo: 'Profissionais que atuam com inflamáveis, combustíveis e processos industriais relacionados à NR 20.', cargaHorariaDetalhe: 'Classe 01', oQueVaiAprender: ['Riscos com inflamáveis e combustíveis', 'Procedimentos de segurança e prevenção', 'Normas específicas da NR 20', 'Condutas adequadas em operações industriais'], instrutor: { nome: 'LM', descricao: 'Instrutor responsável pelo curso.' }, informacoesCurso: ['Conteúdo em conformidade com a legislação vigente', 'Material de apoio em PDF incluso', 'Certificado emitido ao final do curso', 'Acesso ao conteúdo por 12 meses'] },
  { id: 28, titulo: 'NR 20 - Intermediário Classe 02', subtitulo: null, categoria: 'NR', bg: 'from-purple-500 to-purple-700', shadow: 'shadow-purple-300', textColor: 'text-white', emoji: '🛢️', preco: 'R$ 130,00', productId: 'prod_T45xA6tTTBUgBzx0Er2FRrgQ', imagem: '/img/NR20 ClasseII.png', publicoAlvo: 'Profissionais que atuam com inflamáveis, combustíveis e processos industriais relacionados à NR 20.', cargaHorariaDetalhe: 'Classe 02', oQueVaiAprender: ['Riscos com inflamáveis e combustíveis', 'Procedimentos de segurança e prevenção', 'Normas específicas da NR 20', 'Condutas adequadas em operações industriais'], instrutor: { nome: 'LM', descricao: 'Instrutor responsável pelo curso.' }, informacoesCurso: ['Conteúdo em conformidade com a legislação vigente', 'Material de apoio em PDF incluso', 'Certificado emitido ao final do curso', 'Acesso ao conteúdo por 12 meses'] },
  { id: 29, titulo: 'NR 20 - Intermediário Classe 03', subtitulo: null, categoria: 'NR', bg: 'from-purple-500 to-purple-700', shadow: 'shadow-purple-300', textColor: 'text-white', emoji: '🛢️', preco: 'R$ 130,00', productId: 'prod_JPWS5YeKWZDjfcRENa6WNXCY', imagem: '/img/NR20 ClasseII.png', publicoAlvo: 'Profissionais que atuam com inflamáveis, combustíveis e processos industriais relacionados à NR 20.', cargaHorariaDetalhe: 'Classe 03', oQueVaiAprender: ['Riscos com inflamáveis e combustíveis', 'Procedimentos de segurança e prevenção', 'Normas específicas da NR 20', 'Condutas adequadas em operações industriais'], instrutor: { nome: 'LM', descricao: 'Instrutor responsável pelo curso.' }, informacoesCurso: ['Conteúdo em conformidade com a legislação vigente', 'Material de apoio em PDF incluso', 'Certificado emitido ao final do curso', 'Acesso ao conteúdo por 12 meses'] },
  { id: 30, titulo: 'NR 29', subtitulo: '24h', categoria: 'NR', bg: 'from-purple-500 to-purple-700', shadow: 'shadow-purple-300', textColor: 'text-white', emoji: '⚓', preco: 'R$ 130,00', productId: 'prod_bejZEkXpPRbpEbqU6uSxcntT', imagem: '/img/NR29.png', publicoAlvo: 'Profissionais do setor portuário e trabalhadores que atuam em áreas portuárias.', cargaHorariaDetalhe: '24h', oQueVaiAprender: ['Segurança no trabalho portuário', 'Procedimentos e normas aplicáveis', 'Prevenção de acidentes', 'Boas práticas operacionais'], instrutor: { nome: 'LM', descricao: 'Instrutor responsável pelo curso.' }, informacoesCurso: ['Conteúdo em conformidade com a legislação vigente', 'Material de apoio em PDF incluso', 'Certificado emitido ao final do curso', 'Acesso ao conteúdo por 12 meses'] },
  { id: 31, titulo: 'NR 33', subtitulo: '16h', categoria: 'NR', bg: 'from-purple-500 to-purple-700', shadow: 'shadow-purple-300', textColor: 'text-white', emoji: '🕳️', preco: 'R$ 130,00', productId: 'prod_EjqXjuB122DHtrhEzNrFdweY', imagem: '/img/NR 33.png', publicoAlvo: 'Trabalhadores e equipes que atuam em espaços confinados e precisam conhecer os procedimentos de segurança.', cargaHorariaDetalhe: '16h', oQueVaiAprender: ['Segurança em espaços confinados', 'Medidas de controle e prevenção', 'Procedimentos de emergência', 'Boas práticas operacionais'], instrutor: { nome: 'LM', descricao: 'Instrutor responsável pelo curso.' }, informacoesCurso: ['Conteúdo em conformidade com a legislação vigente', 'Material de apoio em PDF incluso', 'Certificado emitido ao final do curso', 'Acesso ao conteúdo por 12 meses'] },
  { id: 32, titulo: 'NR 35 - 2024', subtitulo: '16h', categoria: 'NR', bg: 'from-purple-500 to-purple-700', shadow: 'shadow-purple-300', textColor: 'text-white', emoji: '🧗', preco: 'R$ 130,00', productId: 'prod_chxdawxdacATDEZSecgcw0u6', imagem: '/img/NR35.png', publicoAlvo: 'Profissionais que realizam trabalho em altura e precisam seguir procedimentos de segurança.', cargaHorariaDetalhe: '16h', oQueVaiAprender: ['Segurança no trabalho em altura', 'Medidas de controle e prevenção', 'Procedimentos de emergência', 'Boas práticas operacionais'], instrutor: { nome: 'LM', descricao: 'Instrutor responsável pelo curso.' }, informacoesCurso: ['Conteúdo em conformidade com a legislação vigente', 'Material de apoio em PDF incluso', 'Certificado emitido ao final do curso', 'Acesso ao conteúdo por 12 meses'] },

  // ─── CAPACITAÇÃO PROFISSIONAL ───────────────────────────────────────────
  { id: 33, titulo: 'Atendimento ao Cliente', subtitulo: null, categoria: 'Capacitação', bg: 'from-sky-500 to-cyan-600', shadow: 'shadow-sky-300', textColor: 'text-white', emoji: '🤝', preco: 'R$ 130,00', productId: 'prod_zBfW33WGHP2wxE2MqHsacgMc', imagem: '/img/atendimento_ao_cliente.png', publicoAlvo: 'Profissionais que atendem clientes e desejam melhorar comunicação e qualidade no atendimento.', cargaHorariaDetalhe: 'Carga horária a definir', oQueVaiAprender: ['Atendimento com qualidade e empatia', 'Comunicação e postura profissional', 'Resolução de dúvidas e reclamações', 'Melhoria da experiência do cliente'], instrutor: { nome: 'LM', descricao: 'Instrutor responsável pelo curso.' }, informacoesCurso: ['Conteúdo teórico e prático', 'Material de apoio em PDF incluso', 'Certificado emitido ao final do curso', 'Acesso ao curso por 12 meses'] },
  { id: 34, titulo: 'Atendimento Pré-Hospitalar (APH)', subtitulo: null, categoria: 'Capacitação', bg: 'from-sky-500 to-cyan-600', shadow: 'shadow-sky-300', textColor: 'text-white', emoji: '🏥', preco: 'R$ 130,00', productId: 'prod_zM5MCWfRcdgGQwgQ15dCU0Fh', imagem: '/img/Curso Teorico Atendimento Pré-Hospitalar (APH).png', publicoAlvo: 'Profissionais e estudantes que atuam em serviços de apoio e precisam conhecer atendimento inicial.', cargaHorariaDetalhe: 'Carga horária a definir', oQueVaiAprender: ['Noções de primeiros socorros', 'Atendimento inicial em emergências', 'Reconhecimento de sinais vitais', 'Procedimentos básicos de suporte'], instrutor: { nome: 'LM', descricao: 'Instrutor responsável pelo curso.' }, informacoesCurso: ['Conteúdo técnico e prático', 'Material complementar incluso', 'Certificado emitido ao final', 'Acesso pelo período do curso'] },
  { id: 35, titulo: 'Condutor e Monitor para Passageiros com Mobilidade Reduzida', subtitulo: null, categoria: 'Capacitação', bg: 'from-sky-500 to-cyan-600', shadow: 'shadow-sky-300', textColor: 'text-white', emoji: '♿', preco: 'R$ 130,00', productId: 'prod_jN42b2gpnE4WAx1YArf3WaAT', imagem: '/img/mobilidadereduzida.png', publicoAlvo: 'Condutores e monitores que transportam passageiros com mobilidade reduzida e exigem cuidado e atenção.', cargaHorariaDetalhe: 'Carga horária a definir', oQueVaiAprender: ['Atenção e cuidado com passageiros', 'Procedimentos de embarque e desembarque', 'Comunicação e atendimento inclusivo', 'Segurança e respeito às necessidades específicas'], instrutor: { nome: 'LM', descricao: 'Instrutor responsável pelo curso.' }, informacoesCurso: ['Conteúdo teórico e prático', 'Material de apoio em PDF incluso', 'Certificado emitido ao final do curso', 'Acesso ao curso por 12 meses'] },
  { id: 36, titulo: 'Condução Segura para Motoristas de Caminhão', subtitulo: null, categoria: 'Capacitação', bg: 'from-sky-500 to-cyan-600', shadow: 'shadow-sky-300', textColor: 'text-white', emoji: '🚚', preco: 'R$ 130,00', productId: 'prod_x2wLnDZ3KcCjXT1jn0RqnrSF', imagem: '/img/Condução_Segura_para_Motoristas_de_Caminhão_CAPA.png', publicoAlvo: 'Motoristas profissionais de caminhão que buscam melhorar a condução segura e reduzir riscos.', cargaHorariaDetalhe: 'Carga horária a definir', oQueVaiAprender: ['Condução defensiva e prevenção de acidentes', 'Gerenciamento de estresse e fadiga', 'Técnicas específicas de condução', 'Manutenção preventiva e tecnologia'], instrutor: { nome: 'LM', descricao: 'Instrutor responsável pelo curso.' }, informacoesCurso: ['Conteúdo teórico e prático', 'Material de apoio em PDF incluso', 'Certificado emitido ao final do curso', 'Acesso ao curso por 12 meses'] },
  { id: 37, titulo: 'Condução Segura para Motoristas de Ônibus', subtitulo: null, categoria: 'Capacitação', bg: 'from-sky-500 to-cyan-600', shadow: 'shadow-sky-300', textColor: 'text-white', emoji: '🚍', preco: 'R$ 130,00', productId: 'prod_ddfhPnwER0wpe26XzjSyWS1P', imagem: '/img/Condução_Segura_para_Motoristas_de_Ônibus_CAPA.png', publicoAlvo: 'Motoristas de ônibus que precisam melhorar a condução segura e o atendimento ao passageiro.', cargaHorariaDetalhe: 'Carga horária a definir', oQueVaiAprender: ['Condução defensiva e prevenção de acidentes', 'Gestão de emergências e evacuação', 'Bem-estar do motorista', 'Atendimento ao passageiro'], instrutor: { nome: 'LM', descricao: 'Instrutor responsável pelo curso.' }, informacoesCurso: ['Conteúdo teórico e prático', 'Material de apoio em PDF incluso', 'Certificado emitido ao final do curso', 'Acesso ao curso por 12 meses'] },
  { id: 38, titulo: 'Direção Defensiva', subtitulo: 'Validade 1 ano', categoria: 'Capacitação', bg: 'from-sky-500 to-cyan-600', shadow: 'shadow-sky-300', textColor: 'text-white', emoji: '🛡️', preco: 'R$ 130,00', productId: 'prod_NY5W0RrQ5EXCYLkLy5SqAAk1', imagem: '/img/DIRECAO_DEFENSIVA.png', publicoAlvo: 'Motoristas que desejam melhorar a condução defensiva e reduzir riscos no trânsito.', cargaHorariaDetalhe: 'Validade 1 ano', oQueVaiAprender: ['Condução defensiva e prevenção de acidentes', 'Identificação de riscos na via', 'Manejo de situações de trânsito', 'Boas práticas de direção segura'], instrutor: { nome: 'LM', descricao: 'Instrutor responsável pelo curso.' }, informacoesCurso: ['Conteúdo prático voltado à direção segura', 'Material de apoio em PDF incluso', 'Certificado emitido ao final do curso', 'Acesso ao curso por 12 meses'] },
  { id: 39, titulo: 'Direção Defensiva', subtitulo: 'Validade 2 anos', categoria: 'Capacitação', bg: 'from-sky-500 to-cyan-600', shadow: 'shadow-sky-300', textColor: 'text-white', emoji: '🛡️', preco: 'R$ 130,00', productId: 'prod_c5nGUpLCUeTJuqzn4QqHNymB', imagem: '/img/DIRECAO_DEFENSIVA.png', publicoAlvo: 'Motoristas que desejam melhorar a condução defensiva e reduzir riscos no trânsito.', cargaHorariaDetalhe: 'Validade 2 anos', oQueVaiAprender: ['Condução defensiva e prevenção de acidentes', 'Identificação de riscos na via', 'Manejo de situações de trânsito', 'Boas práticas de direção segura'], instrutor: { nome: 'LM', descricao: 'Instrutor responsável pelo curso.' }, informacoesCurso: ['Conteúdo prático voltado à direção segura', 'Material de apoio em PDF incluso', 'Certificado emitido ao final do curso', 'Acesso ao curso por 12 meses'] },
  { id: 40, titulo: 'Manutenção Automotiva para Profissionais do Transporte', subtitulo: null, categoria: 'Capacitação', bg: 'from-sky-500 to-cyan-600', shadow: 'shadow-sky-300', textColor: 'text-white', emoji: '🔧', preco: 'R$ 130,00', productId: 'prod_QCNcdq1Pj5rpDe0pGQKRqKLN', imagem: '/img/Manutenção_Automotiva_para_Profissionais_do_Transporte_CAPA.png', publicoAlvo: 'Profissionais do transporte, motoristas e mecânicos que desejam aprender manutenção automotiva.', cargaHorariaDetalhe: 'Carga horária a definir', oQueVaiAprender: ['Manutenção preventiva', 'Manutenção corretiva básica', 'Sistemas e diagnóstico eletrônico', 'Boas práticas operacionais'], instrutor: { nome: 'LM', descricao: 'Instrutor responsável pelo curso.' }, informacoesCurso: ['Conteúdo teórico e prático', 'Material de apoio em PDF incluso', 'Certificado emitido ao final do curso', 'Acesso ao curso por 12 meses'] },
  { id: 41, titulo: 'Segurança e Saúde no Transporte de Cargas', subtitulo: null, categoria: 'Capacitação', bg: 'from-sky-500 to-cyan-600', shadow: 'shadow-sky-300', textColor: 'text-white', emoji: '🦺', preco: 'R$ 130,00', productId: 'prod_N33AzaXnzfDphJkCeUMkGNtc', imagem: '/img/Segurança_e_Saúde_no_Transporte_de_Cargas_CAPA.png', publicoAlvo: 'Profissionais do transporte de cargas que buscam melhorar a segurança e a saúde no trabalho.', cargaHorariaDetalhe: 'Carga horária a definir', oQueVaiAprender: ['Princípios básicos de segurança', 'Manejo seguro de cargas', 'Saúde ocupacional no transporte', 'Emergências e primeiros socorros'], instrutor: { nome: 'LM', descricao: 'Instrutor responsável pelo curso.' }, informacoesCurso: ['Conteúdo teórico e prático', 'Material de apoio em PDF incluso', 'Certificado emitido ao final do curso', 'Acesso ao curso por 12 meses'] },
  { id: 42, titulo: 'Transporte de Cargas', subtitulo: null, categoria: 'Capacitação', bg: 'from-sky-500 to-cyan-600', shadow: 'shadow-sky-300', textColor: 'text-white', emoji: '📦', preco: 'R$ 130,00', productId: 'prod_LRs5GASW2wwRaLc4ws1PYQdk', imagem: '/img/TRANSPORTE_DE_CARGAS_CAPA.png', publicoAlvo: 'Motoristas de veículos de carga, operadores logísticos e gestores de frota.', cargaHorariaDetalhe: 'Carga horária a definir', oQueVaiAprender: ['Introdução ao transporte de cargas', 'Condução defensiva e segurança viária', 'Direção econômica', 'Tecnologias e gestão operacional'], instrutor: { nome: 'LM', descricao: 'Instrutor responsável pelo curso.' }, informacoesCurso: ['Conteúdo teórico e prático', 'Material de apoio em PDF incluso', 'Certificado emitido ao final do curso', 'Acesso ao curso por 12 meses'] },
  { id: 43, titulo: 'Direção Econômica e Tecnologia no Transporte', subtitulo: null, categoria: 'Capacitação', bg: 'from-sky-500 to-cyan-600', shadow: 'shadow-sky-300', textColor: 'text-white', emoji: '♻️', preco: 'R$ 130,00', productId: 'prod_ypaJAUBycf4zW5GQ6nm3GwBT', imagem: '/img/Direção_Econômica_e_Tecnologia_no_Transporte_CAPA.png', publicoAlvo: 'Profissionais de transporte que buscam eficiência, economia e uso de tecnologia.', cargaHorariaDetalhe: 'Carga horária a definir', oQueVaiAprender: ['Direção econômica', 'Tecnologias aplicadas ao transporte', 'Gestão de frota e eficiência', 'Boas práticas para redução de custos'], instrutor: { nome: 'LM', descricao: 'Instrutor responsável pelo curso.' }, informacoesCurso: ['Conteúdo teórico e prático', 'Material de apoio em PDF incluso', 'Certificado emitido ao final do curso', 'Acesso ao curso por 12 meses'] },
  { id: 44, titulo: 'Gestão Logística e Otimização de Processos', subtitulo: null, categoria: 'Capacitação', bg: 'from-sky-500 to-cyan-600', shadow: 'shadow-sky-300', textColor: 'text-white', emoji: '📊', preco: 'R$ 130,00', productId: 'prod_xkBaNKeh5BkHB6BhhRuqgFaa', imagem: '/img/Gestão_Logística_e_Otimização_de_Processos_na_Cadeia_de_Suprimentos_CAPA.png', publicoAlvo: 'Profissionais da área logística e gestão da cadeia de suprimentos.', cargaHorariaDetalhe: 'Carga horária a definir', oQueVaiAprender: ['Introdução à logística', 'Estratégias de otimização', 'Gestão da cadeia de suprimentos', 'Tecnologias e boas práticas'], instrutor: { nome: 'LM', descricao: 'Instrutor responsável pelo curso.' }, informacoesCurso: ['Conteúdo teórico e prático', 'Material de apoio em PDF incluso', 'Certificado emitido ao final do curso', 'Acesso ao curso por 12 meses'] },
  { id: 45, titulo: 'Gestão de Fretes', subtitulo: null, categoria: 'Capacitação', bg: 'from-sky-500 to-cyan-600', shadow: 'shadow-sky-300', textColor: 'text-white', emoji: '💰', preco: 'R$ 130,00', productId: 'prod_RqfqhAjLQZE4p00J5BnTUb6Q', imagem: '/img/Gestão_de_Fretes_-_Estratégias_para_Eficiência_no_Transporte_de_Mercadorias_CAPA.png', publicoAlvo: 'Profissionais e empresários do setor de transporte e logística.', cargaHorariaDetalhe: 'Carga horária a definir', oQueVaiAprender: ['Como calcular o frete', 'Controle de custos', 'Estratégias de otimização', 'Gestão financeira e logística'], instrutor: { nome: 'LM', descricao: 'Instrutor responsável pelo curso.' }, informacoesCurso: ['Conteúdo teórico e prático', 'Material de apoio em PDF incluso', 'Certificado emitido ao final do curso', 'Acesso ao curso por 12 meses'] },
  { id: 46, titulo: 'Gestão de Pneus no Transporte', subtitulo: null, categoria: 'Capacitação', bg: 'from-sky-500 to-cyan-600', shadow: 'shadow-sky-300', textColor: 'text-white', emoji: '🔵', preco: 'R$ 130,00', productId: 'prod_GCnrJBLmeLJ4aGxYsq13EzJH', imagem: '/img/Gestão_de_Pneus_no_Transporte_CAPA.png', publicoAlvo: 'Profissionais de transporte e gestão de frota que querem otimizar o uso de pneus.', cargaHorariaDetalhe: 'Carga horária a definir', oQueVaiAprender: ['Fundamentos de pneus no transporte', 'Manutenção preventiva e corretiva', 'Estratégias de compra e renovação', 'Tecnologias e tendências em pneus'], instrutor: { nome: 'LM', descricao: 'Instrutor responsável pelo curso.' }, informacoesCurso: ['Conteúdo teórico e prático', 'Material de apoio em PDF incluso', 'Certificado emitido ao final do curso', 'Acesso ao curso por 12 meses'] },
  { id: 47, titulo: 'Monitor de Transporte Escolar', subtitulo: null, categoria: 'Capacitação', bg: 'from-sky-500 to-cyan-600', shadow: 'shadow-sky-300', textColor: 'text-white', emoji: '🏫', preco: 'R$ 130,00', productId: 'prod_t1AXgkGWfDUAeUbBMcR1gpRj', imagem: '/img/monitor_escolar.png', publicoAlvo: 'Condutores e monitores de transporte escolar que precisam seguir normas de segurança e atendimento.', cargaHorariaDetalhe: 'Carga horária a definir', oQueVaiAprender: ['Atenção ao transporte escolar', 'Procedimentos de segurança com passageiros', 'Condução responsável e atendimento', 'Normas e prevenção de riscos'], instrutor: { nome: 'LM', descricao: 'Instrutor responsável pelo curso.' }, informacoesCurso: ['Conteúdo teórico e prático', 'Material de apoio em PDF incluso', 'Certificado emitido ao final do curso', 'Acesso ao curso por 12 meses'] },
  { id: 48, titulo: 'Noções Básicas de Primeiros Socorros', subtitulo: null, categoria: 'Capacitação', bg: 'from-sky-500 to-cyan-600', shadow: 'shadow-sky-300', textColor: 'text-white', emoji: '🩺', preco: 'R$ 130,00', productId: 'prod_zTyngueZwbjMNNmwpajuUUqb', imagem: '/img/primeiros_socorros.png', publicoAlvo: 'Profissionais e estudantes que atuam em serviços de apoio e precisam conhecer atendimento inicial.', cargaHorariaDetalhe: 'Carga horária a definir', oQueVaiAprender: ['Noções de primeiros socorros', 'Atendimento inicial em emergências', 'Reconhecimento de sinais vitais', 'Procedimentos básicos de suporte'], instrutor: { nome: 'LM', descricao: 'Instrutor responsável pelo curso.' }, informacoesCurso: ['Conteúdo técnico e prático', 'Material complementar incluso', 'Certificado emitido ao final', 'Acesso pelo período do curso'] },
  { id: 49, titulo: 'Prevenção e Combate a Incêndio', subtitulo: null, categoria: 'Capacitação', bg: 'from-sky-500 to-cyan-600', shadow: 'shadow-sky-300', textColor: 'text-white', emoji: '🧯', preco: 'R$ 130,00', productId: 'prod_HDWtpTCEWeuQSacKzdjZfFcU', imagem: '/img/combate_incendio.png', publicoAlvo: 'Colaboradores e profissionais que trabalham em ambientes com risco de incêndio.', cargaHorariaDetalhe: 'Carga horária a definir', oQueVaiAprender: ['Prevenção e combate a incêndios', 'Riscos e medidas de segurança', 'Uso de extintores e equipamentos', 'Procedimentos em situações de emergência'], instrutor: { nome: 'LM', descricao: 'Instrutor responsável pelo curso.' }, informacoesCurso: ['Conteúdo técnico e prático', 'Material complementar incluso', 'Certificado emitido ao final', 'Acesso pelo período do curso'] },

  // ─── AVANÇADOS / TRABALHO ─────────────────────────────────────────────
  { id: 50, titulo: 'Curso de Junta Administrativa e Recursos de Infração (JARI)', subtitulo: '16h', categoria: 'Capacitação', bg: 'from-sky-500 to-cyan-600', shadow: 'shadow-sky-300', textColor: 'text-white', emoji: '⚖️', preco: 'R$ 400,00', productId: 'prod_hynh5HsHS1Kf6exXHbSfNrPP', imagem: '/img/jari.png', publicoAlvo: 'Condutores e profissionais do trânsito que precisam entender processos administrativos e recursos de infração.', cargaHorariaDetalhe: '16h', oQueVaiAprender: ['Entendimento de processos administrativos', 'Recurso de infração e defesa', 'Legislação e procedimentos do trânsito', 'Tomada de decisões e regularização'], instrutor: { nome: 'LM', descricao: 'Instrutor responsável pelo curso.' }, informacoesCurso: ['Conteúdo teórico e prático', 'Material de apoio em PDF incluso', 'Certificado emitido ao final do curso', 'Acesso ao curso por 12 meses'] },
  { id: 51, titulo: 'Formação para Instrutor de CFC', subtitulo: '180h', categoria: 'Instrutor', bg: 'from-indigo-500 to-purple-600', shadow: 'shadow-indigo-300', textColor: 'text-white', emoji: '👨‍🏫', preco: 'R$ 3000,00', productId: 'prod_33FUMPnkHYhPAkw6356CZU6r', imagem: '/img/FORMAÇÃO_INSTRUTOR_DE_TRANSITO (1).png', publicoAlvo: 'Profissionais e gestores do setor de trânsito que desejam se capacitar e ampliar sua atuação.', cargaHorariaDetalhe: '180h', oQueVaiAprender: ['Fundamentos legais e administrativos', 'Responsabilidades e competências da função', 'Boas práticas de gestão e ensino', 'Atualização profissional na área'], instrutor: { nome: 'LM', descricao: 'Instrutor responsável pelo curso.' }, informacoesCurso: ['Conteúdo teórico e prático', 'Material de apoio em PDF incluso', 'Certificado emitido ao final do curso', 'Acesso ao curso por 12 meses'] },
  { id: 52, titulo: 'Complementação para Instrutor de CFC', subtitulo: '60h', categoria: 'Instrutor', bg: 'from-indigo-500 to-purple-600', shadow: 'shadow-indigo-300', textColor: 'text-white', emoji: '📚', preco: 'R$ 1400,00', productId: 'prod_RMj0TcXsf6yuYNUgGg1NTDQG', imagem: '/img/FORMAÇÃO_INSTRUTOR_DE_TRANSITO (1).png', publicoAlvo: 'Profissionais e gestores do setor de trânsito que desejam se capacitar e ampliar sua atuação.', cargaHorariaDetalhe: '60h', oQueVaiAprender: ['Fundamentos legais e administrativos', 'Responsabilidades e competências da função', 'Boas práticas de gestão e ensino', 'Atualização profissional na área'], instrutor: { nome: 'LM', descricao: 'Instrutor responsável pelo curso.' }, informacoesCurso: ['Conteúdo teórico e prático', 'Material de apoio em PDF incluso', 'Certificado emitido ao final do curso', 'Acesso ao curso por 12 meses'] },
  { id: 53, titulo: 'Atualização para Instrutor de CFC', subtitulo: '20h', categoria: 'Instrutor', bg: 'from-indigo-500 to-purple-600', shadow: 'shadow-indigo-300', textColor: 'text-white', emoji: '🔄', preco: 'R$ 600,00', productId: 'prod_Jxhp1BhjYeRNmLBtZ0ujuUsz', imagem: '/img/FORMAÇÃO_INSTRUTOR_DE_TRANSITO (1).png', publicoAlvo: 'Profissionais e gestores do setor de trânsito que desejam se capacitar e ampliar sua atuação.', cargaHorariaDetalhe: '20h', oQueVaiAprender: ['Fundamentos legais e administrativos', 'Responsabilidades e competências da função', 'Boas práticas de gestão e ensino', 'Atualização profissional na área'], instrutor: { nome: 'LM', descricao: 'Instrutor responsável pelo curso.' }, informacoesCurso: ['Conteúdo teórico e prático', 'Material de apoio em PDF incluso', 'Certificado emitido ao final do curso', 'Acesso ao curso por 12 meses'] },
  { id: 54, titulo: 'Formação para Diretor Geral de CFC', subtitulo: '40h', categoria: 'Diretor', bg: 'from-teal-500 to-emerald-600', shadow: 'shadow-teal-300', textColor: 'text-white', emoji: '👔', preco: 'R$ 1200,00', productId: 'prod_a2MuyQ6uzXqKEarMTmCkr35y', imagem: '/img/FORMAÇÃO_INSTRUTOR_DE_TRANSITO (1).png', publicoAlvo: 'Profissionais e gestores do setor de trânsito que desejam se capacitar e ampliar sua atuação.', cargaHorariaDetalhe: '40h', oQueVaiAprender: ['Fundamentos legais e administrativos', 'Responsabilidades e competências da função', 'Boas práticas de gestão e ensino', 'Atualização profissional na área'], instrutor: { nome: 'LM', descricao: 'Instrutor responsável pelo curso.' }, informacoesCurso: ['Conteúdo teórico e prático', 'Material de apoio em PDF incluso', 'Certificado emitido ao final do curso', 'Acesso ao curso por 12 meses'] },
  { id: 55, titulo: 'Formação para Diretor de Ensino de CFC', subtitulo: '40h', categoria: 'Diretor', bg: 'from-teal-500 to-emerald-600', shadow: 'shadow-teal-300', textColor: 'text-white', emoji: '📝', preco: 'R$ 1200,00', productId: 'prod_xrn2fHzLLHEpQuGC14rj5NPL', imagem: '/img/FORMAÇÃO_INSTRUTOR_DE_TRANSITO (1).png', publicoAlvo: 'Profissionais e gestores do setor de trânsito que desejam se capacitar e ampliar sua atuação.', cargaHorariaDetalhe: '40h', oQueVaiAprender: ['Fundamentos legais e administrativos', 'Responsabilidades e competências da função', 'Boas práticas de gestão e ensino', 'Atualização profissional na área'], instrutor: { nome: 'LM', descricao: 'Instrutor responsável pelo curso.' }, informacoesCurso: ['Conteúdo teórico e prático', 'Material de apoio em PDF incluso', 'Certificado emitido ao final do curso', 'Acesso ao curso por 12 meses'] },
  { id: 56, titulo: 'Atualização para Diretor Geral de CFC', subtitulo: '20h', categoria: 'Diretor', bg: 'from-teal-500 to-emerald-600', shadow: 'shadow-teal-300', textColor: 'text-white', emoji: '🔄', preco: 'R$ 700,00', productId: 'prod_XrffrJ3F1JzjyPBq1MrGKdmM', imagem: '/img/FORMAÇÃO_INSTRUTOR_DE_TRANSITO (1).png', publicoAlvo: 'Profissionais e gestores do setor de trânsito que desejam se capacitar e ampliar sua atuação.', cargaHorariaDetalhe: '20h', oQueVaiAprender: ['Fundamentos legais e administrativos', 'Responsabilidades e competências da função', 'Boas práticas de gestão e ensino', 'Atualização profissional na área'], instrutor: { nome: 'LM', descricao: 'Instrutor responsável pelo curso.' }, informacoesCurso: ['Conteúdo teórico e prático', 'Material de apoio em PDF incluso', 'Certificado emitido ao final do curso', 'Acesso ao curso por 12 meses'] },
  { id: 57, titulo: 'Atualização para Diretor de Ensino de CFC', subtitulo: '20h', categoria: 'Diretor', bg: 'from-teal-500 to-emerald-600', shadow: 'shadow-teal-300', textColor: 'text-white', emoji: '🔄', preco: 'R$ 700,00', productId: 'prod_SxgfWuhZa4ud4Z1UPWRNcCfs', imagem: '/img/FORMAÇÃO_INSTRUTOR_DE_TRANSITO (1).png', publicoAlvo: 'Profissionais e gestores do setor de trânsito que desejam se capacitar e ampliar sua atuação.', cargaHorariaDetalhe: '20h', oQueVaiAprender: ['Fundamentos legais e administrativos', 'Responsabilidades e competências da função', 'Boas práticas de gestão e ensino', 'Atualização profissional na área'], instrutor: { nome: 'LM', descricao: 'Instrutor responsável pelo curso.' }, informacoesCurso: ['Conteúdo teórico e prático', 'Material de apoio em PDF incluso', 'Certificado emitido ao final do curso', 'Acesso ao curso por 12 meses'] },
  { id: 58, titulo: 'Formação para Examinador de Trânsito', subtitulo: '28h', categoria: 'Examinador', bg: 'from-amber-500 to-orange-600', shadow: 'shadow-amber-300', textColor: 'text-white', emoji: '📋', preco: 'R$ 900,00', productId: 'prod_Rh3peHPAJKuGdTeGDr0hkCW0', imagem: '/img/FORMAÇÃO_INSTRUTOR_DE_TRANSITO (1).png', publicoAlvo: 'Profissionais e gestores do setor de trânsito que desejam se capacitar e ampliar sua atuação.', cargaHorariaDetalhe: '28h', oQueVaiAprender: ['Fundamentos legais e administrativos', 'Responsabilidades e competências da função', 'Boas práticas de gestão e ensino', 'Atualização profissional na área'], instrutor: { nome: 'LM', descricao: 'Instrutor responsável pelo curso.' }, informacoesCurso: ['Conteúdo teórico e prático', 'Material de apoio em PDF incluso', 'Certificado emitido ao final do curso', 'Acesso ao curso por 12 meses'] },
  { id: 59, titulo: 'Atualização para Examinador de Trânsito', subtitulo: '20h', categoria: 'Examinador', bg: 'from-amber-500 to-orange-600', shadow: 'shadow-amber-300', textColor: 'text-white', emoji: '🔄', preco: 'R$ 440,00', productId: 'prod_gmR1aBzxgerXxhaH336AN3Hr', imagem: '/img/FORMAÇÃO_INSTRUTOR_DE_TRANSITO (1).png', publicoAlvo: 'Profissionais e gestores do setor de trânsito que desejam se capacitar e ampliar sua atuação.', cargaHorariaDetalhe: '20h', oQueVaiAprender: ['Fundamentos legais e administrativos', 'Responsabilidades e competências da função', 'Boas práticas de gestão e ensino', 'Atualização profissional na área'], instrutor: { nome: 'LM', descricao: 'Instrutor responsável pelo curso.' }, informacoesCurso: ['Conteúdo teórico e prático', 'Material de apoio em PDF incluso', 'Certificado emitido ao final do curso', 'Acesso ao curso por 12 meses'] },
  { id: 60, titulo: 'Pós-Graduação em Gestão e Direito de Trânsito', subtitulo: '360h', categoria: 'Pós-Graduação', bg: 'from-slate-700 to-slate-900', shadow: 'shadow-slate-400', textColor: 'text-white', emoji: '🎓', preco: 'R$ 2000,00', productId: 'prod_p1kpZX1hLpPmw4UFtrTJbUND', imagem: '/img/pos_gestao.png', publicoAlvo: 'Profissionais que desejam aprofundar conhecimentos em gestão, educação e segurança no trânsito.', cargaHorariaDetalhe: '360h', oQueVaiAprender: ['Fundamentos de gestão e educação no trânsito', 'Aprofundamento em segurança viária', 'Análise de políticas e processos', 'Aplicação prática em contextos profissionais'], instrutor: { nome: 'LM', descricao: 'Instrutor responsável pelo curso.' }, informacoesCurso: ['Conteúdo teórico e prático', 'Material de apoio em PDF incluso', 'Certificado emitido ao final do curso', 'Acesso ao curso por 12 meses'] },
  { id: 61, titulo: 'Pós-Graduação em Gestão e Educação para o Trânsito', subtitulo: '360h', categoria: 'Pós-Graduação', bg: 'from-slate-700 to-slate-900', shadow: 'shadow-slate-400', textColor: 'text-white', emoji: '🎓', preco: 'R$ 2000,00', productId: 'prod_1SKTZy4auj0JhZtaLKezuS4r', imagem: '/img/pos_educacao.png', publicoAlvo: 'Profissionais que desejam aprofundar conhecimentos em gestão, educação e segurança no trânsito.', cargaHorariaDetalhe: '360h', oQueVaiAprender: ['Fundamentos de gestão e educação no trânsito', 'Aprofundamento em segurança viária', 'Análise de políticas e processos', 'Aplicação prática em contextos profissionais'], instrutor: { nome: 'LM', descricao: 'Instrutor responsável pelo curso.' }, informacoesCurso: ['Conteúdo teórico e prático', 'Material de apoio em PDF incluso', 'Certificado emitido ao final do curso', 'Acesso ao curso por 12 meses'] },
  { id: 62, titulo: 'Pós-Graduação em Engenharia de Tráfego e Segurança Viária', subtitulo: '360h', categoria: 'Pós-Graduação', bg: 'from-slate-700 to-slate-900', shadow: 'shadow-slate-400', textColor: 'text-white', emoji: '🎓', preco: 'R$ 2000,00', productId: 'prod_JFKLB6LpPykd62yKmkHx4aSx', imagem: '/img/pos_engenharia.png', publicoAlvo: 'Profissionais que desejam aprofundar conhecimentos em gestão, educação e segurança no trânsito.', cargaHorariaDetalhe: '360h', oQueVaiAprender: ['Fundamentos de gestão e educação no trânsito', 'Aprofundamento em segurança viária', 'Análise de políticas e processos', 'Aplicação prática em contextos profissionais'], instrutor: { nome: 'LM', descricao: 'Instrutor responsável pelo curso.' }, informacoesCurso: ['Conteúdo teórico e prático', 'Material de apoio em PDF incluso', 'Certificado emitido ao final do curso', 'Acesso ao curso por 12 meses'] },
]

// ─────────────────────────────────────────────────────────────────────────
// Gera slugs únicos e preenche descrições padrão quando não informadas
// ─────────────────────────────────────────────────────────────────────────
const slugsUsados = new Set<string>()

export const courses: Course[] = coursesInput.map((c) => {
  const slugBase = slugify(c.subtitulo ? `${c.titulo}-${c.subtitulo}` : c.titulo)
  let slug = slugBase
  if (slugsUsados.has(slug)) slug = `${slugBase}-${c.id}`
  slugsUsados.add(slug)

  return {
    ...c,
    slug,
    descricaoCurta: c.descricaoCurta ?? `Curso de ${c.categoria.toLowerCase()} — ${c.titulo}${c.subtitulo ? ` (${c.subtitulo})` : ''}.`,
    descricaoLonga: c.descricaoLonga ?? gerarDescricaoPadrao(c),
  }
})

export function getCourseBySlug(slug: string): Course | undefined {
  return courses.find((c) => c.slug === slug)
}

// ─────────────────────────────────────────────────────────────────────────
// Preço, requisitos, estados e validações (igual ao que você já tinha)
// ─────────────────────────────────────────────────────────────────────────
export function parsePreco(preco: string): number {
  return parseFloat(preco.replace('R$', '').replace(/\./g, '').replace(',', '.').trim())
}

export const REQUISITOS_CURSOS: Record<string, string[]> = {
  'Carga Indivisível Formação': ['C', 'D', 'E'],
  'Carga Indivisível Atualização': ['C', 'D', 'E'],
  'Coletivo de Passageiros Formação': ['D', 'E'],
  'Coletivo de Passageiros Atualização': ['D', 'E'],
  'Emergência Formação': ['A', 'B', 'C', 'D', 'E'],
  'Emergência Atualização': ['A', 'B', 'C', 'D', 'E'],
  'Escolar Formação': ['D', 'E'],
  'Escolar Atualização': ['D', 'E'],
  'Produtos Perigosos - MOPP Formação': ['B', 'C', 'D', 'E'],
  'Produtos Perigosos - MOPP Atualização': ['B', 'C', 'D', 'E'],
}

export const ESTADOS_RECICLAGEM: Record<number, string[]> = {
  11: ['AC', 'AL', 'DF', 'MA', 'MT', 'PE', 'RJ', 'SC', 'SE', 'SP', 'TO'],
  12: ['DF', 'ES', 'GO', 'MT', 'MS', 'PE', 'RJ', 'RS', 'SC', 'SP'],
  13: ['AC', 'AL', 'CE', 'DF', 'ES', 'GO', 'MA', 'MT', 'MS', 'PE', 'PR', 'RJ', 'RS', 'SC', 'SE', 'SP', 'TO'],
}

export type User = {
  _id: string
  nome: string
  email: string
  whatsapp: string
  cpf: string
  cnh: string
  categoriaCnh: string[]
  ufCnh: string
  dataNascimento: string
  endereco: {
    logradouro: string
    numero: string
    bairro: string
    cidade: string
    estado: string
    cep: string
  }
  access: boolean
  createdAt: string
  updatedAt: string
  __v: number
}

export type ValidationError = {
  hasError: boolean
  idadeOk: boolean
  categoriaOk: boolean
  requiredCategories: string[]
  userCategories: string[]
}

export type ValidationErrorEstado = {
  hasError: boolean
  estadoOk: boolean
  allowedStates: string[]
  userState: string
}

export function calcularIdade(dataNascimento: string): number {
  const hoje = new Date()
  const nascimento = new Date(dataNascimento)
  let idade = hoje.getFullYear() - nascimento.getFullYear()
  const mes = hoje.getMonth() - nascimento.getMonth()
  if (mes < 0 || (mes === 0 && hoje.getDate() < nascimento.getDate())) idade--
  return idade
}

export function validarRequisitoCurso(course: Course, user: User): ValidationError {
  const idadeOk = calcularIdade(user.dataNascimento) >= 21
  const requiredCategories = REQUISITOS_CURSOS[course.titulo] || []
  const categoriaOk = requiredCategories.length === 0 || requiredCategories.some(cat => user.categoriaCnh.includes(cat))
  return { hasError: !idadeOk || !categoriaOk, idadeOk, categoriaOk, requiredCategories, userCategories: user.categoriaCnh }
}

export function validarEstadoReciclagem(courseId: number, user: User): ValidationErrorEstado {
  const allowedStates = ESTADOS_RECICLAGEM[courseId] || []
  const userState = user.endereco?.estado?.toUpperCase() || ''
  const estadoOk = allowedStates.length === 0 || allowedStates.includes(userState)
  return { hasError: !estadoOk, estadoOk, allowedStates, userState }
}
